# Sikistirilmis takas hizli oldugu icin agresif kullanilir.
vm.swappiness = 100
vm.vfs_cache_pressure = 50
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
vm.min_free_kbytes = 32768
kernel.sysrq = 1
