/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YasalRouteImport } from './routes/yasal'
import { Route as SohbetRouteImport } from './routes/sohbet'
import { Route as KosullarRouteImport } from './routes/kosullar'
import { Route as IhracatUyumRouteImport } from './routes/ihracat-uyum'
import { Route as IadeRouteImport } from './routes/iade'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CevrimdisiRouteImport } from './routes/cevrimdisi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as ApiPublicRelayRouteImport } from './routes/api/public/relay'
import { Route as ApiPublicQueueRouteImport } from './routes/api/public/queue'
import { Route as ApiPublicPushRouteImport } from './routes/api/public/push'
import { Route as ApiPublicPingRouteImport } from './routes/api/public/ping'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicIsoRouteImport } from './routes/api/public/iso'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicGecitRouteImport } from './routes/api/public/gecit'
import { Route as ApiPublicEnrollRouteImport } from './routes/api/public/enroll'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronOfflineCheckRouteImport } from './routes/api/public/cron/offline-check'

const YasalRoute = YasalRouteImport.update({
  id: '/yasal',
  path: '/yasal',
  getParentRoute: () => rootRouteImport,
} as any)
const SohbetRoute = SohbetRouteImport.update({
  id: '/sohbet',
  path: '/sohbet',
  getParentRoute: () => rootRouteImport,
} as any)
const KosullarRoute = KosullarRouteImport.update({
  id: '/kosullar',
  path: '/kosullar',
  getParentRoute: () => rootRouteImport,
} as any)
const IhracatUyumRoute = IhracatUyumRouteImport.update({
  id: '/ihracat-uyum',
  path: '/ihracat-uyum',
  getParentRoute: () => rootRouteImport,
} as any)
const IadeRoute = IadeRouteImport.update({
  id: '/iade',
  path: '/iade',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CevrimdisiRoute = CevrimdisiRouteImport.update({
  id: '/cevrimdisi',
  path: '/cevrimdisi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRelayRoute = ApiPublicRelayRouteImport.update({
  id: '/api/public/relay',
  path: '/api/public/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQueueRoute = ApiPublicQueueRouteImport.update({
  id: '/api/public/queue',
  path: '/api/public/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushRoute = ApiPublicPushRouteImport.update({
  id: '/api/public/push',
  path: '/api/public/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPingRoute = ApiPublicPingRouteImport.update({
  id: '/api/public/ping',
  path: '/api/public/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIsoRoute = ApiPublicIsoRouteImport.update({
  id: '/api/public/iso',
  path: '/api/public/iso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGecitRoute = ApiPublicGecitRouteImport.update({
  id: '/api/public/gecit',
  path: '/api/public/gecit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnrollRoute = ApiPublicEnrollRouteImport.update({
  id: '/api/public/enroll',
  path: '/api/public/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronOfflineCheckRoute =
  ApiPublicCronOfflineCheckRouteImport.update({
    id: '/api/public/cron/offline-check',
    path: '/api/public/cron/offline-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cevrimdisi': typeof CevrimdisiRoute
  '/chat': typeof ChatRoute
  '/gizlilik': typeof GizlilikRoute
  '/iade': typeof IadeRoute
  '/ihracat-uyum': typeof IhracatUyumRoute
  '/kosullar': typeof KosullarRoute
  '/sohbet': typeof SohbetRoute
  '/yasal': typeof YasalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/public/enroll': typeof ApiPublicEnrollRoute
  '/api/public/gecit': typeof ApiPublicGecitRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/iso': typeof ApiPublicIsoRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/api/public/queue': typeof ApiPublicQueueRoute
  '/api/public/relay': typeof ApiPublicRelayRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/cron/offline-check': typeof ApiPublicCronOfflineCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cevrimdisi': typeof CevrimdisiRoute
  '/chat': typeof ChatRoute
  '/gizlilik': typeof GizlilikRoute
  '/iade': typeof IadeRoute
  '/ihracat-uyum': typeof IhracatUyumRoute
  '/kosullar': typeof KosullarRoute
  '/sohbet': typeof SohbetRoute
  '/yasal': typeof YasalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/public/enroll': typeof ApiPublicEnrollRoute
  '/api/public/gecit': typeof ApiPublicGecitRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/iso': typeof ApiPublicIsoRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/api/public/queue': typeof ApiPublicQueueRoute
  '/api/public/relay': typeof ApiPublicRelayRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/cron/offline-check': typeof ApiPublicCronOfflineCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cevrimdisi': typeof CevrimdisiRoute
  '/chat': typeof ChatRoute
  '/gizlilik': typeof GizlilikRoute
  '/iade': typeof IadeRoute
  '/ihracat-uyum': typeof IhracatUyumRoute
  '/kosullar': typeof KosullarRoute
  '/sohbet': typeof SohbetRoute
  '/yasal': typeof YasalRoute
  '/api/chat': typeof ApiChatRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/public/enroll': typeof ApiPublicEnrollRoute
  '/api/public/gecit': typeof ApiPublicGecitRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/iso': typeof ApiPublicIsoRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/api/public/queue': typeof ApiPublicQueueRoute
  '/api/public/relay': typeof ApiPublicRelayRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/cron/offline-check': typeof ApiPublicCronOfflineCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cevrimdisi'
    | '/chat'
    | '/gizlilik'
    | '/iade'
    | '/ihracat-uyum'
    | '/kosullar'
    | '/sohbet'
    | '/yasal'
    | '/api/chat'
    | '/api/translate'
    | '/api/public/enroll'
    | '/api/public/gecit'
    | '/api/public/health'
    | '/api/public/iso'
    | '/api/public/openapi.json'
    | '/api/public/ping'
    | '/api/public/push'
    | '/api/public/queue'
    | '/api/public/relay'
    | '/api/public/telemetry'
    | '/api/public/cron/offline-check'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cevrimdisi'
    | '/chat'
    | '/gizlilik'
    | '/iade'
    | '/ihracat-uyum'
    | '/kosullar'
    | '/sohbet'
    | '/yasal'
    | '/api/chat'
    | '/api/translate'
    | '/api/public/enroll'
    | '/api/public/gecit'
    | '/api/public/health'
    | '/api/public/iso'
    | '/api/public/openapi.json'
    | '/api/public/ping'
    | '/api/public/push'
    | '/api/public/queue'
    | '/api/public/relay'
    | '/api/public/telemetry'
    | '/api/public/cron/offline-check'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/cevrimdisi'
    | '/chat'
    | '/gizlilik'
    | '/iade'
    | '/ihracat-uyum'
    | '/kosullar'
    | '/sohbet'
    | '/yasal'
    | '/api/chat'
    | '/api/translate'
    | '/api/public/enroll'
    | '/api/public/gecit'
    | '/api/public/health'
    | '/api/public/iso'
    | '/api/public/openapi.json'
    | '/api/public/ping'
    | '/api/public/push'
    | '/api/public/queue'
    | '/api/public/relay'
    | '/api/public/telemetry'
    | '/api/public/cron/offline-check'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CevrimdisiRoute: typeof CevrimdisiRoute
  ChatRoute: typeof ChatRoute
  GizlilikRoute: typeof GizlilikRoute
  IadeRoute: typeof IadeRoute
  IhracatUyumRoute: typeof IhracatUyumRoute
  KosullarRoute: typeof KosullarRoute
  SohbetRoute: typeof SohbetRoute
  YasalRoute: typeof YasalRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiPublicEnrollRoute: typeof ApiPublicEnrollRoute
  ApiPublicGecitRoute: typeof ApiPublicGecitRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicIsoRoute: typeof ApiPublicIsoRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicPingRoute: typeof ApiPublicPingRoute
  ApiPublicPushRoute: typeof ApiPublicPushRoute
  ApiPublicQueueRoute: typeof ApiPublicQueueRoute
  ApiPublicRelayRoute: typeof ApiPublicRelayRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
  ApiPublicCronOfflineCheckRoute: typeof ApiPublicCronOfflineCheckRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yasal': {
      id: '/yasal'
      path: '/yasal'
      fullPath: '/yasal'
      preLoaderRoute: typeof YasalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sohbet': {
      id: '/sohbet'
      path: '/sohbet'
      fullPath: '/sohbet'
      preLoaderRoute: typeof SohbetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosullar': {
      id: '/kosullar'
      path: '/kosullar'
      fullPath: '/kosullar'
      preLoaderRoute: typeof KosullarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ihracat-uyum': {
      id: '/ihracat-uyum'
      path: '/ihracat-uyum'
      fullPath: '/ihracat-uyum'
      preLoaderRoute: typeof IhracatUyumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iade': {
      id: '/iade'
      path: '/iade'
      fullPath: '/iade'
      preLoaderRoute: typeof IadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cevrimdisi': {
      id: '/cevrimdisi'
      path: '/cevrimdisi'
      fullPath: '/cevrimdisi'
      preLoaderRoute: typeof CevrimdisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/relay': {
      id: '/api/public/relay'
      path: '/api/public/relay'
      fullPath: '/api/public/relay'
      preLoaderRoute: typeof ApiPublicRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/queue': {
      id: '/api/public/queue'
      path: '/api/public/queue'
      fullPath: '/api/public/queue'
      preLoaderRoute: typeof ApiPublicQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push': {
      id: '/api/public/push'
      path: '/api/public/push'
      fullPath: '/api/public/push'
      preLoaderRoute: typeof ApiPublicPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ping': {
      id: '/api/public/ping'
      path: '/api/public/ping'
      fullPath: '/api/public/ping'
      preLoaderRoute: typeof ApiPublicPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iso': {
      id: '/api/public/iso'
      path: '/api/public/iso'
      fullPath: '/api/public/iso'
      preLoaderRoute: typeof ApiPublicIsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gecit': {
      id: '/api/public/gecit'
      path: '/api/public/gecit'
      fullPath: '/api/public/gecit'
      preLoaderRoute: typeof ApiPublicGecitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enroll': {
      id: '/api/public/enroll'
      path: '/api/public/enroll'
      fullPath: '/api/public/enroll'
      preLoaderRoute: typeof ApiPublicEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/offline-check': {
      id: '/api/public/cron/offline-check'
      path: '/api/public/cron/offline-check'
      fullPath: '/api/public/cron/offline-check'
      preLoaderRoute: typeof ApiPublicCronOfflineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CevrimdisiRoute: CevrimdisiRoute,
  ChatRoute: ChatRoute,
  GizlilikRoute: GizlilikRoute,
  IadeRoute: IadeRoute,
  IhracatUyumRoute: IhracatUyumRoute,
  KosullarRoute: KosullarRoute,
  SohbetRoute: SohbetRoute,
  YasalRoute: YasalRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiPublicEnrollRoute: ApiPublicEnrollRoute,
  ApiPublicGecitRoute: ApiPublicGecitRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicIsoRoute: ApiPublicIsoRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicPingRoute: ApiPublicPingRoute,
  ApiPublicPushRoute: ApiPublicPushRoute,
  ApiPublicQueueRoute: ApiPublicQueueRoute,
  ApiPublicRelayRoute: ApiPublicRelayRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
  ApiPublicCronOfflineCheckRoute: ApiPublicCronOfflineCheckRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
